package task

import (
	"encoding/json"
	"fmt"
	"gfast/app/model/admin/user_online"
	"gfast/app/service/admin/dict_service"
	"gfast/boot"
	"io/ioutil"
	"net/http"

	"github.com/goflyfox/gtoken/gtoken"
	"github.com/gogf/gf/encoding/gjson"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/os/gcache"
	"github.com/gogf/gf/util/gconv"
)

func init() {
	var task1 Entity
	task1.FuncName = "test1"
	task1.Param = nil
	task1.Run = Test1
	Add(task1)

	var task2 Entity
	task2.FuncName = "test2"
	task2.Param = nil
	task2.Run = Test2
	Add(task2)

	var checkUserOnline Entity
	checkUserOnline.FuncName = "checkUserOnline"
	checkUserOnline.Param = nil
	checkUserOnline.Run = CheckUserOnline
	Add(checkUserOnline)

	var getaccess Entity
	getaccess.FuncName = "getaccess"
	getaccess.Param = nil
	getaccess.Run = Getaccess
	Add(getaccess)
}

// 获得字典的corpid  和 corpsecret  生成token

var Corpidtest string
var Corpsecret1test string
var Tmvaluetest string

//公共token
var AccessToken string

func Getaccess() {
	// dite, err := dict_service.GetDictWithDataByType("access_token")
	// 获取 关键信息并且全局
	corpid1, err := dict_service.GetDictDataById(74)
	if err != nil {
		fmt.Println("获取失败")
	}

	Corpidtest = corpid1.DictValue

	corpsecret1, err := dict_service.GetDictDataById(75)
	if err != nil {
		fmt.Println("获取失败")
	}
	Corpsecret1test = corpsecret1.DictValue
	tmvalue, err := dict_service.GetDictDataById(76)

	if err != nil {
		fmt.Println("获取失败")
	}
	Tmvaluetest = tmvalue.DictValue
	fmt.Println(Corpidtest, Corpsecret1test, Tmvaluetest)

	Weixintoken()
}

type AutoGenerated struct {
	Errcode     int    `json:"errcode"`
	Errmsg      string `json:"errmsg"`
	AccessToken string `json:"access_token"`
	ExpiresIn   int    `json:"expires_in"`
}

// 获得token
func Weixintoken() {

	url := "https://qyapi.weixin.qq.com/cgi-bin/gettoken?" + Corpidtest + "&" + Corpsecret1test
	fmt.Println(url)
	resp, err := http.Get(url)
	// 关闭连接
	defer resp.Body.Close()
	if err != nil {
		fmt.Println("失败")
	}
	var bodytest1 AutoGenerated
	bodytest, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		fmt.Println(err)
	}

	err1 := json.Unmarshal(bodytest, &bodytest1)

	if err1 != nil {
		fmt.Println("错误")
	}
	AccessToken = "access_token=" + bodytest1.AccessToken

	fmt.Println(AccessToken)
	List()

}

//无参测试
func Test1() {
	println("无参测试")
	// Getaccess()
}

//传参测试
func Test2() {
	//获取参数
	task := GetByName("test2")
	if task == nil {
		return
	}
	for _, v := range task.Param {
		println(v)
	}
}

//检查在线用户
func CheckUserOnline() {
	param := &user_online.ReqListSearch{
		PageNum:  1,
		PageSize: 50,
	}
	var total int
	for {
		var (
			list []*user_online.Entity
			err  error
		)
		total, _, list, err = user_online.GetOnlineListPage(param, true)
		if err != nil {
			g.Log().Error(err)
			break
		}
		if list == nil {
			break
		}
		for _, entity := range list {
			onlineInfo := GetOnlineInfo(entity.Token)
			if onlineInfo == nil {
				user_online.Model.Delete("id", entity.Id)
			}
		}
		param.PageNum++
		if param.PageNum*param.PageSize >= total {
			break
		}
	}

}

//通过token获取登录用户数据
func GetOnlineInfo(token string) g.Map {
	uuid, userKey := GetUuidUserKeyByToken(token)
	cacheKey := boot.AdminGfToken.CacheKey + userKey
	switch boot.AdminGfToken.CacheMode {
	case gtoken.CacheModeCache:
		userCacheValue, _ := gcache.Get(cacheKey)
		if userCacheValue == nil {
			return nil
		}
		return gconv.Map(userCacheValue)
	case gtoken.CacheModeRedis:
		var userCache g.Map
		userCacheJson, err := g.Redis().Do("GET", cacheKey)
		if err != nil {
			g.Log().Error("[GToken]cache get error", err)
			return nil
		}
		if userCacheJson == nil {
			return nil
		}
		err = gjson.DecodeTo(userCacheJson, &userCache)
		if err != nil {
			g.Log().Error("[GToken]cache get json error", err)
			return nil
		}
		if uuid != userCache["uuid"] {
			return nil
		}
		return userCache
	}
	return nil
}

//通过token获取uuid和userKey
func GetUuidUserKeyByToken(token string) (uuid, userKey string) {
	decryptToken := boot.AdminGfToken.DecryptToken(token)
	if !decryptToken.Success() {
		return
	}
	userKey = decryptToken.GetString("userKey")
	uuid = decryptToken.GetString("uuid")
	return
}

// // 获得字典的corpid  和 corpsecret  生成token

// func Getaccess() {
// 	// dite, err := dict_service.GetDictWithDataByType("access_token")

// 	ditelist, err := dict_service.GetDictWithDataByType("access_token", "", "")

// 	if err != nil {
// 		fmt.Println("获取失败")
// 	}

// 	for _, v := range ditelist {
// 		fmt.Println(v)
// 	}

// }
